---
title: "Probability and Statistics | PPE"
date: 2025-10-12
---

Welcome to [Prelims Probability and Statistics](https://canvas.ox.ac.uk/courses/294545/modules)! This page outlines our teaching arrangements for the 2025-2026 academic year. For the full schedule, including times and locations for our classes and tutorials, please see the [syllabus](syllabus.qmd). Each class will begin with a short [quiz](#quizzes), but you won't have any work to submit beforehand. To get the most out of the course, your punctual attendance at all classes is expected. If you are unwell and unable to attend, please send me an [email](mailto:jasmin.baier@bsg.ox.ac.uk) to let me know.

## Course Logistics
Before diving into the details below, log onto canvas and read the [Overview and Instructions](https://canvas.ox.ac.uk/courses/294545/pages/3-dot-0-overview-and-instructions-2?module_item_id=2960418). This will give you a clear picture of how the course is structured.

## Collections
You will have one or two 90-minute mock exams, which we call "collections." There will definitely be one at the start of Trinity Term (April). We might also have an earlier one at the beginning of Hilary Term (January); I'll decide on this based on our progress in the first term. We will discuss the final details in class, and I will post more information here later in the year.

## Quizzes 

We will begin every class with a short, closed-book quiz. I will mark them and get them back to you in the following session. The quizzes are designed to help you solidify your knowledge and will have two parts:

- Review Questions: This part will be a random selection from the [review questions](review-questions.qmd) assigned for that class. Since you have these in advance, preparing them thoroughly is the key to doing well and staying on top of the material. Because you are given these questions in advance, you should be able to answer them correctly on the quiz. If you cannot, this means that you have not come to class adequately prepared. 

- Challenge Questions: The quiz may also include some new, more challenging questions based on topics we've covered in previous classes. You won't see these beforehand. Their purpose is to help you think more deeply about the concepts and get valuable practice for your collections and final exam.

## Before Each Class 
1. Watch the [lecture videos](https://canvas.ox.ac.uk/courses/294545/pages/3-dot-1-lecture-material-recordings-and-lecture-slides?module_item_id=2960419) listed on the [syllabus](syllabus.qmd). 
2. Take active notes
    - Note down key definitions and formulas.
    - Creating flashcards (with a tool like [Anki](https://apps.ankiweb.net), for example) is an excellent way to memorize the core concepts.
3. Solve the assigned [review questions](review-questions.qmd). 
4. Repeat as needed:
    - If you get stuck on the review questions, it’s a sign to revisit the lecture videos and slides before attempting them again.
    - Working with friends is highly recommended!
    - Make a note of anything that you find confusing and bring it with you to class.
    
## After Each Class 
Complete the [problem set](problem-sets.qmd). Then watch the associated [Demonstration Lecture](https://canvas.ox.ac.uk/courses/294545/pages/3-dot-2-demonstration-lecture-material?module_item_id=2960420) for solutions and explanations. Your problem set questions are neither collected nor marked, but they will serve as inspiration for future quiz and collections problems. 

## Revision Tutorials

Later in the year, during Trinity Term (TT), I will run dedicated revision tutorials. These sessions will be a mix of content review and practice problems to help you prepare for your final exams. I will share more details closer to the time.

*Acknowledgement: This course and website heavily rely on material prepared by [Francis DiTraglia](https://ditraglia.com/) who is kindly allowing me to use his texts, quizzes & review questions*